FROM centos:7
MAINTAINER Sander <mail@sandervanvugt.nl>

# Add repo file
COPY ./sander.repo /etc/yum.repos.d/

# Install cool software
RUN     yum -y update 
RUN     yum -y install bash nmap iproute 
# Note that since the clean step at line #10 is in a different layer, it will not actually do anything because it does not have access to the previous layers t clean them.
# Check ./Containerfile-v2 for how to fix that and note the difference in image sizes
RUN     yum clean all

ENTRYPOINT ["/usr/bin/nmap"]
CMD ["-sn", "172.17.0.0/24"]